services:
  server:
    restart: always
    build:
      context: .
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev
      - PORT=8000
      - HOST=localhost
      - LOG_LEVEL=debug
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DB_HOST=jbx-dev-db
      - DB_PORT=5432
      - DB_USER=devuser
      - DB_PASS=devpass
      - DB_NAME=devdatabase
      - REDIS_HOST=jbx-redis
      - REDIS_PORT=6379
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm run start:dev

  postgres:
    image: postgres:13-alpine
    # image: postgres:13
    container_name: jbx-dev-db
    volumes:
      - jukebox-pg-data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
    environment:
      # - POSTGRES_DB=devdatabase
      - POSTGRES_MULTIPLE_DATABASES=devdatabase,test
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      
  redis:
    image: redis:alpine
    container_name: jbx-redis
    # ports:
    #   - 6379:6379

volumes:
  jukebox-pg-data:
