name: Code Linting

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Packages
        run: npm install
      - name: Run Eslint
        run: npm run lint


